# Makefile for Windows

CC = gcc


CFLAGS = -Wall -O2 -D_WIN32 -Iinclude -Llib


LIBS = -lws2_32 -lwintun -lcrypto -lssl


TARGET = VPNCore.exe

SRCS = \
    common.c \
    config.c \
    connection.c \
    encryption.c \
    logging.c \
    main.c \
    tunnel.c \
    utils.c

OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
    $(CC) $(OBJS) -o $(TARGET) $(LIBS)
%.o: %.c
    $(CC) $(CFLAGS) -c $< -o $@

clean:
    del /Q *.o $(TARGET)

.PHONY: all clean
